### ISSUE TITLE
Feature request: pull requests using hub

### ISSUE THREAD

**Issue by willmcclellan** [idanarye/vim-merginal#4]
Really liking Merginal, great work! I've recently started using [hub for github](https://github.com/github/hub) and thought it would be great if merginal allowed you to create a pull request using hub.

The command is `$ hub pull-request` which opens a vim buffer to type your PR title and description.

**Comment by idanarye** [comment]
**Note**: I did not install `hub` - I assume it works like most command line tools.

I won't add this feature to the main Merginal plugin because I don't want Merginal features that depend on Git extensions/plugins. My only dependencies are Git and Fugitive(and optionally vimproc, but no feature actually depends on it - they only work better with it under Windows). This, however, does not mean you run hub commands from the Merginal branch list!

I should probably add it to the documentation, but Merginal provides an API for extending it's functionality(mainly adding commands to the special Merginal buffers that can access the information on the git object under the cursor. Adding new Merginal is also possible, the API doesn't help as much in that case...). This is mainly done by using the `User Merginal_<something>` autocommand hooks to create the commands for the special buffers and the `merginal#<something>Details` functions to get the chosen item's information. So, you could write something like this in your `.vimrc`:
```vim
autocmd User Merginal_BranchList nnoremap <buffer> gpr :execute '!hub pull-request -h ' . merginal#branchDetails('.').handle<Cr>
```
and when you open the Merginal buffer, place the cursor on a branch, and type `gpr` - it'll run the shell command `hub pull-request -h <the-chosen-branch>` .

Do keep in mind that this will not open a Vim buffer for you to type your PR's title and description. Rather:
* If you run it on Windows, or in the terminal version on Linux, it'll open a brand new Vim instance for your PR. Your old instance of Vim will be waiting for the shell command to finish and you won't have access to it's buffers.
* If you run it in gVim on Linux, you'll get gibrish on the screen and eventually it'll go back to your session with the PR either being canceled or opened with default title(I don't really know what `hub` does in that case).

If you want to open it in a buffer in your current instance of Vim(like Fugitive open's a buffer for your to type your commit message) you'll have to use a Vim plugin dedicated for `hub`. A quick search yields [Vim-Mahewin-Hub](https://github.com/hobbestigrou/vim-mahewin-hub), but it doesn't seem to solve the buffer-in-new-instance-of-vim problem.

Creating such a plugin shouldn't be that hard. You can also send a PR for Mahewin(better have all the functionality in one place). It should be a plugin that provides a command for it, so it can be used without Merginal. You can even add autocompletion for branch names - it's not that hard:

```vim
function! s:gitBranches(argLead, cmdLine, cursorPos)
    let l:result = split(system('git branch --column=never --no-color'), '\v[\r\n]+')
    let l:result = map(l:result, 'v:val[2 :]')
    let l:argLen = len(a:argLead)
    if 0 < l:argLen
        let l:result = filter(l:result, 'v:val[: l:argLen - 1] == a:argLead')
    endif
    return l:result
endfunction
command! -complete=customlist,s:gitBranches -nargs=1 HubPullRequest call hub#pullRequest(<q-args>)
```

Such plugin - which can be used without Merginal - can easily hook into Merginal to add itself as a command:
```vim
autocmd User Merginal_BranchList nnoremap <buffer> gpr call hub#pullRequest(merginal#branchDetails('.').handle)<Cr>
```

**Comment by willmcclellan** [comment]
Wow, thanks for the awesome reply :star: 

The autocmd command in my vimrc did the trick perfectly and I don't mind the buffer in a new vim instance so much. It would be nice to have it open in the current instance like fugitive so I might look into that when I get time… as  you say it looks quite simple but I have done anything with vim plugins before.

**Comment by idanarye** [comment]
If you don't have much experience with VimScript you'll have a hard time trying to understand Fugitive's source code, since it uses a lot of meta-programming to define all the commands, but basically what it does to open a buffer for you to write your commit message is:

1. Temporarily set the `GIT_EDITOR` environment variable to something that always fails(specifically - the command `false`).
2. Call `git commit`, which will try to invoke `GIT_EDITOR` and fail, but create the commit message file inside the `.git` directory with the template git generates for you.
3. Open the commit message file in a new buffer.
4. When that buffer is closed - call `git commit` again, but this time use the `-F` flag to direct it to the commit message file we just edited.

This method has some pitfalls which Tim Pope addressed in Fugitive and you'll have to address too if you use this method, but you can always create the buffer on your own and send the data to `hub pull-request` using the `-F` flag.
