### ISSUE TITLE
Quick help in the Merginal window

### ISSUE THREAD

**Issue by lazywei** [idanarye/vim-merginal#7]
Hi,

Thanks for the amazing plugin. However, I'm feeling it would be great if we can have a "quick help" in the Merginal's window because there are too many key mappings for me to memorize. For example, in NERDTree's window, I can `" Press ? for help`. After pressing `?`, I get a bunch of helpful hints.

How do you think?

Thanks.

**Comment by idanarye** [comment]
This might be a good idea. I've also seen a complaint somewhere on Reddit that keymaps are harder to remember than commands, and I think these two changes can go well together(define the command, and use some mechanism to register both a keymap and the help text for it)

**Comment by wikimatze** [comment]
Maybe I can help with this issue - that's a feature I always wanted to know how to implement it. What do you think @idanarye?

**Comment by idanarye** [comment]
@wikimatze You can give it a go if you want. The main challenge IMO is keeping the quick help synchronized with the actual command, so we won't forget to update the quick-help text when we add new commands

**Comment by wikimatze** [comment]
Hi, I created a first draft under https://github.com/wikimatze/vim-merginal/tree/help-menue. I created the command `:MerginalHelp`. The output is not the best, I tried to get close to NERDTree but lacks the nice view, for which I have problems. What do you think?

**Comment by idanarye** [comment]
@wikimatze I don't like this mechanism. NERDTree's help is nice because you can open it with a single key, read what you need to read, and close it again with the same key. `:MerginalHelp`, on the other hand, changes the Merginal buffer - so if you were, for example, viewing the diff files list with an older commit from a side branch, and you run `:MerginalHelp`, once you are done reading the part of the help you were looking for you won't be able to open the branch list again, look for that side branch again, `gl` it again, look for the specific commit again and `gd` it again.

Another thing I don't like in it is that it's a command and not a keymap. Vim already has a command for opening a new window that'll show help - good old `:help ...`.  And it's superior to `:MerginalHelp` in every way - it has autocompletion, is has syntax hightlighting, it has tag navigation, it opens in a wider, easier-to-read window and it doesn't close the Merginal buffer you are working on. The only reason to prefer the quick-help over the vimdocs is for quickness- and `:MerginalHelp` does not offer quickness.

~~If~~ When I implement the quick-help feature, I want it to display the keymaps relevant to the Merginal buffer the user currently has open - and this means it can't be a global command - it has to be something only callable from the Merginal buffer.

**Comment by wikimatze** [comment]
I agree.

**Comment by saravanak** [comment]
@idanarye  This is an attempt at this using the approach followed by NerdTree as you had suggested. Please find the work at https://github.com/saravanak/vim-merginal/tree/help. If everything is fine, I will create a pull request for the same. Some pointers on the implementation

- the flag to show the help is local to a buffer. So a help text on one window won't affect the help text on the other window.
- the help is printed on the same buffer similar to how NerdTree does it. I thought it was more intuitive than having displayed on another window. (which was my initial approach)

**Comment by idanarye** [comment]
@saravanak I haven't looked too much into the code, but it looks pretty nice :thumbsup: Your mechanism can later be extended to add command versions of the keymaps([someone complained about it on Reddit almost a year ago](https://www.reddit.com/r/vim/comments/2tp3ok/vimmerginal_fugitive_extension_to_manage_and/co1v9g9)).

There are a few things I want to change once I pull this:

1. The keymaps library should not be in `lib/merginal/keymaps.vim` but in `autoload/merginal/keymaps.vim`. That's the structure I use in my other plugins, and it better adheres vim module system. Instead of declaring the functions as e.g. `s:KeyMap.Create` and invoking them as `g:MerginalKeyMap.Create` they'll be both declared and invoked as `merginal#keymaps#create`. This also means we won't need `call merginal#loadClassFiles()` - Vim's autoload mechanism will load them automatically.

2. The display format will be refactored. The empty line should be between the help and the list, not above the list. I'll also try to implement some smart line-wrapping.

3. I'll try to get rid of `merginal#initKeyMappings` - after making `keymaps.vim` an _autoload_ it should be fine to set the keymaps directly in `merginal.vim`.

**Comment by saravanak** [comment]
Thanks for the comments @idanarye . If you need help in doing any of the changes that you have listed, I am all game. :+1:

**Comment by wikimatze** [comment]
Sounds like a great enhancement. @saravanak is it really enough to copy only the class from the NERDTree? There are copy/paste comments inside. Just my opinion.

**Comment by idanarye** [comment]
@saravanak  - would you mind creating a PR for that branch? Direct it to `develop`, not to `master`

**Comment by saravanak** [comment]
@idanarye , do you want the changes you outlined to be done?  

@wikimatze, I did not remove the copy/paste as it was just a "first round of review" case. Will clean up and submit on the new PR. BTW, there are some additions to the NERDTree based class(like dynamic arg calls ) added in my version. See [here](https://github.com/saravanak/vim-merginal/commit/3987925ff7adc97721f14bc08d8c321643ffb4cf#diff-9bd91ee2fef612c021a72807fde393e4R72) for the same. Apologies for  I missed your update for a long time.

**Comment by idanarye** [comment]
@saravanak If you can please. If not I'll do them.

**Comment by wikimatze** [comment]
@saravanak no problem, thanks for your additions.

**Comment by idanarye** [comment]
Implementation is in `develop`. It's not as pretty as I want it yet - I'll get to making it prettier soon(I hope).

The refactor I needed to make this sensible was big enough for a major version bump!
