### ISSUE TITLE
Add --no-ff option for a git merge

### ISSUE THREAD

**Issue by wikimatze** [idanarye/vim-merginal#8]
Hi,

I'm very pleased with your plugin and tried your `M` command the first time. And since I'm a fan of nice git-graphs, it would be nice if there is place for a `no--ff` variant of the merge.

It's in line https://github.com/idanarye/vim-merginal/blob/develop/autoload/merginal.vim#L550. Is such a feature okay and what should the mapping be in your eyes?

Bests

Matthias

**Comment by idanarye** [comment]
Yea, the feature is easy, the hard part is choosing the correct keymap.

My first thought was using `mf` for `--ff-only` and `mF` for `--no-ff`, since in many command line utilities the capital single-letter-switch is used as the reverse of the small single-letter-switch with the same letter. However:

 - This convention can not be found in Vim's keymaps(except `gu` vs `gU`, which doesn't count because it's about case changing and the upper/lower `u` is for converting to upper/lower case) - when a map has an uppercase version and a lowercase version the meaning is usually a different motion...
 - The more often used command will probably be `mF` - which is the harder one to type


Maybe 'mn`?

**Comment by wikimatze** [comment]
Hi, I think `mf` and `mn` are fine.

**Comment by idanarye** [comment]
Actually, I just looked at it seems that I forgot that `mf` is already occupied(merging using Fugitive's `:Gmerge`). Well, `--ff-only` was a nice-to-have anyways(no one actually requested it), so I'll just abide YAGNI, use `mn` for `--no-ff`, and think of a keymap for `--ff-only` is someone will ever need it.
